services:  
  hoppscotch:
    image: hoppscotch/hoppscotch
    container_name: hoppscotch
    networks:
      - apollo
    ports:
      - "3015:3000"
      - "3115:3100"
      - "3170:3170"
    env_file:
      - ./data/hoppscotch/hoppscotch.env
    restart: unless-stopped
    depends_on:
      - hoppscotch-db
    mem_limit: 256m # Limite máximo de memória
    cpus: 1 # Limite máximo de cpu

  hoppscotch-db:
    image: postgres:17.2-alpine3.21
    container_name: hoppscotch-db
    networks:
      - apollo
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: hoppscotch
    volumes:
      - ./data/hoppscotch/hoppscotch-dump.sql:/docker-entrypoint-initdb.d/hoppscotch-dump.sql
    mem_limit: 256m # Limite máximo de memória
    cpus: 1 # Limite máximo de cpu

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_SERVER_PORT: 8081
    ports:
      - "8081:8978"
    volumes:
      - ./data/cbeaver:/opt/cloudbeaver/workspace
    networks:
      - apollo
    restart: unless-stopped
    mem_limit: 512m # Limite máximo de memória
    cpus: 1 # Limite máximo de cpu

networks:
  apollo:
    external: true
    driver: bridge